services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-backend_db}
      POSTGRES_USER: ${POSTGRES_USER:-backend_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-backend_password}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-backend_user} -d ${POSTGRES_DB:-backend_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql-data:
    driver: local
