name: 'Continuous Integration'

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/pr.yaml

  deploy:
    name: Deploy
    needs: quality-assurance
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
          chmod 600 ~/.ssh/github
          cat >>~/.ssh/config <<END
          Host target
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github
            LogLevel ERROR
            StrictHostKeyChecking no
          END
      - name: Deploy Application
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH || 'django_template' }}
        run: |
          ssh target "cd ${DEPLOY_PATH}/ && \
            git pull && \
            docker compose build && \
            SKIP_MIGRATIONS=true SKIP_COLLECTSTATIC=true docker compose up -d && \
            docker compose exec -T app python -m core.manage migrate && \
            docker compose exec -T app python -m core.manage collectstatic --no-input && \
            docker compose restart app"

      - name: Verify Deployment
        run: |
          ssh target "cd ${DEPLOY_PATH}/ && \
            docker compose exec -T app python -m core.manage check --deploy && \
            curl -f http://localhost:8000/health/ || exit 1"
